name: test

on:
  pull_request:
    branches:
    - master

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Git Branch test
        run: |
          git config user.name "Update Branch"
          git config user.email github-actions@github.com
      - name: Checkout master and Current Branch test
        run: |
          git checkout test
      - name: Merge Master Branch in test
        run: |
          git merge master --no-edit -m "Merged main branch on $(date +%F)"  
      - name: Push the test
        run: |
          git push origin test
